@echo off
REM Script de Détection Automatique de l'IP du Téléphone (Windows)
REM Utilisation: detect-ip.bat

setlocal enabledelayedexpansion

echo ==========================================
echo CameraStream - Auto IP Detection (Windows)
echo ==========================================
echo.

REM Vérifier que adb est disponible
where adb >nul 2>&1
if !errorlevel! neq 0 (
    echo [ERROR] adb not found. Please install Android SDK tools.
    echo https://developer.android.com/tools/adb
    pause
    exit /b 1
)

echo [INFO] Searching for connected devices...
echo.

REM Lister les devices
adb devices | findstr "device" >nul
if !errorlevel! neq 0 (
    echo [ERROR] No devices found.
    echo.
    echo To fix this:
    echo 1. Connect your Android device via USB
    echo 2. Enable USB Debugging (Settings - Developer Options)
    echo 3. Run: adb devices
    echo 4. Accept the RSA key fingerprint on your device
    echo 5. Run this script again
    echo.
    pause
    exit /b 1
)

echo [OK] Connected devices:
adb devices | findstr "device"
echo.

REM Détection IP - Méthode 1: getprop
echo [INFO] Detecting IP address (Method 1: getprop)...
for /f %%A in ('adb shell getprop dhcp.wlan0.ipaddress') do set IP=%%A

REM Méthode 2: ip route
if "!IP!"=="" (
    echo [WARNING] Method 1 failed, trying Method 2: ip route...
    for /f "tokens=*" %%A in ('adb shell ip route ^| findstr /R "src"') do (
        for %%B in (%%A) do (
            setlocal disabledelayedexpansion
            set VAL=%%B
            setlocal enabledelayedexpansion
            if "!VAL!" equ "src" (
                for /f %%C in ('adb shell ip route ^| findstr /R "src"') do (
                    for %%D in (%%C) do (
                        set IP=%%D
                        goto :found_ip
                    )
                )
            )
        )
    )
)

:found_ip

if "!IP!"=="" (
    echo.
    echo [ERROR] Could not automatically detect IP address.
    echo.
    echo Manual options:
    echo.
    echo 1. Check the app itself:
    echo    - Open the CameraStream app on your device
    echo    - The IP address is displayed in the Admin screen
    echo.
    echo 2. Check device settings:
    echo    - Settings - Wi-Fi - [Connected Network] - Properties
    echo.
    echo 3. Check your router:
    echo    - Open router admin interface
    echo    - Look for connected devices
    echo.
    echo 4. Use ADB to check:
    echo    - adb shell getprop dhcp.wlan0.ipaddress
    echo.
    pause
    exit /b 1
)

echo.
echo ==========================================
echo [OK] IP Address Detected Successfully!
echo ==========================================
echo.
echo [INFO] Device IP: !IP!
echo [INFO] Streaming URL: http://!IP!:8080/stream
echo [INFO] Status URL: http://!IP!:8080/status
echo.

REM Créer un fichier de configuration
set CONFIG_FILE=camera_stream_config.bat
(
    echo REM CameraStream Configuration
    echo REM Auto-generated by detect-ip.bat
    echo REM Do not edit manually
    echo.
    echo set CAMERA_IP=!IP!
    echo set CAMERA_PORT=8080
    echo set STREAM_URL=http://!IP!:8080/stream
    echo set STATUS_URL=http://!IP!:8080/status
) > !CONFIG_FILE!

echo [INFO] Configuration saved to: !CONFIG_FILE!
echo.

REM Tester la connexion
echo [TEST] Testing connection...
timeout /t 1 /nobreak >nul

REM Simple port test (peut ne pas fonctionner parfaitement sur Windows)
echo Testing access to http://!IP!:8080/status...
curl -s -m 3 http://!IP!:8080/status >nul 2>&1
if !errorlevel! equ 0 (
    echo [OK] Connection successful! Server is running.
    echo.
    echo Next steps:
    echo 1. Start streaming in the CameraStream app
    echo 2. Open in browser: http://!IP!:8080/stream
    echo 3. Or use: curl http://!IP!:8080/status
    echo 4. Or open in VLC: Media - Open Network Stream - http://!IP!:8080/stream
) else (
    echo [WARNING] Connection test may have failed.
    echo.
    echo Possible reasons:
    echo - Server not running (start it in the app)
    echo - Wrong IP address
    echo - Firewall blocking port 8080
    echo - Network connectivity issue
    echo.
    echo Debug commands:
    echo   adb shell netstat -tuln ^| findstr 8080
    echo   adb shell ping -c 1 8.8.8.8
)

echo.
echo ==========================================
echo.
echo Usage:
echo.
echo Run the config file to set variables:
echo   camera_stream_config.bat
echo.
echo Then use:
echo   curl %STREAM_URL% ^> video.mjpeg
echo   VLC: Media - Open Network Stream - %STREAM_URL%
echo.

pause

