#!/bin/bash
# Script de Détection Automatique de l'IP du Téléphone
# Utilisation: ./detect-ip.sh

echo "=========================================="
echo "CameraStream - Auto IP Detection"
echo "=========================================="
echo ""

# Vérifier que adb est installé
if ! command -v adb &> /dev/null; then
    echo "❌ adb not found. Please install Android SDK tools."
    echo "   https://developer.android.com/tools/adb"
    exit 1
fi

echo "🔍 Searching for connected devices..."
echo ""

# Lister les devices connectés
DEVICES=$(adb devices | grep -v "List of" | grep -v "^$" | grep "device$")

if [ -z "$DEVICES" ]; then
    echo "❌ No devices found."
    echo ""
    echo "📱 To fix this:"
    echo "1. Connect your Android device via USB"
    echo "2. Enable USB Debugging (Settings → Developer Options)"
    echo "3. Run: adb devices"
    echo "4. Accept the RSA key fingerprint on your device"
    echo "5. Run this script again"
    exit 1
fi

echo "✅ Found connected devices:"
echo "$DEVICES" | while read -r line; do
    echo "  - $line"
done
echo ""

# Détecter l'IP - Méthode 1: via ip route
echo "🔎 Detecting IP address (Method 1: ip route)..."
IP=$(adb shell ip route | grep -oP '(?<=src )[\d.]+' | head -1)

# Méthode 2: via getprop si Méthode 1 ne fonctionne pas
if [ -z "$IP" ]; then
    echo "⚠️  Method 1 failed, trying Method 2: getprop..."
    IP=$(adb shell getprop dhcp.wlan0.ipaddress)
fi

# Méthode 3: via ifconfig
if [ -z "$IP" ]; then
    echo "⚠️  Method 2 failed, trying Method 3: ifconfig..."
    IP=$(adb shell ifconfig wlan0 | grep "inet " | awk '{print $2}' | head -1)
fi

# Méthode 4: via netstat
if [ -z "$IP" ]; then
    echo "⚠️  Method 3 failed, trying Method 4: netstat..."
    IP=$(adb shell netstat -an | grep ESTABLISHED | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
fi

# Si toutes les méthodes échouent
if [ -z "$IP" ]; then
    echo ""
    echo "❌ Could not automatically detect IP address."
    echo ""
    echo "📋 Manual options:"
    echo ""
    echo "1. Check the app itself:"
    echo "   - Open the CameraStream app on your device"
    echo "   - The IP address is displayed in the Admin screen"
    echo ""
    echo "2. Check device settings:"
    echo "   - Settings → Wi-Fi → [Connected Network] → Properties"
    echo ""
    echo "3. Check your router:"
    echo "   - Open router admin interface"
    echo "   - Look for connected devices"
    echo ""
    echo "4. Use ping to find it:"
    echo "   - ping camera-stream.local  (if mDNS is enabled)"
    echo "   - nmap -sn 192.168.1.0/24  (scan your subnet)"
    exit 1
fi

# Nettoyer l'IP (enlever les espaces/caractères invisibles)
IP=$(echo "$IP" | xargs)

echo ""
echo "=========================================="
echo "✅ IP Address Detected Successfully!"
echo "=========================================="
echo ""
echo "📱 Device IP: $IP"
echo "🌐 Streaming URL: http://$IP:8080/stream"
echo "📊 Status URL: http://$IP:8080/status"
echo ""

# Créer un fichier de configuration
CONFIG_FILE=".camera_stream_config"
cat > "$CONFIG_FILE" << EOF
# CameraStream Configuration
# Auto-generated by detect-ip.sh
# Do not edit manually

CAMERA_IP=$IP
CAMERA_PORT=8080
STREAM_URL=http://$IP:8080/stream
STATUS_URL=http://$IP:8080/status
EOF

echo "💾 Configuration saved to: $CONFIG_FILE"
echo ""

# Tester la connexion
echo "🧪 Testing connection..."
if timeout 3 bash -c "echo > /dev/tcp/$IP/8080" 2>/dev/null; then
    echo "✅ Connection successful! Server is running."
    echo ""
    echo "📖 Next steps:"
    echo "1. Start streaming in the CameraStream app"
    echo "2. Open in browser: http://$IP:8080/stream"
    echo "3. Or use: curl http://$IP:8080/status"
    echo "4. Or use: ffplay http://$IP:8080/stream"
else
    echo "⚠️  Connection test failed."
    echo ""
    echo "Possible reasons:"
    echo "- Server not running (start it in the app)"
    echo "- Wrong IP address"
    echo "- Firewall blocking port 8080"
    echo "- Network connectivity issue"
    echo ""
    echo "Debug commands:"
    echo "  adb shell netstat -tuln | grep 8080"
    echo "  adb shell ping -c 1 8.8.8.8"
fi

echo ""
echo "=========================================="
echo ""
echo "💡 Usage:"
echo ""
echo "Source the config file in your shell:"
echo "  . $CONFIG_FILE"
echo ""
echo "Then use:"
echo "  curl \$STREAM_URL > video.mjpeg"
echo "  ffplay \$STREAM_URL"
echo "  vlc \$STREAM_URL"
echo ""

